name: "Podcast Generator"
author: "Encre Informatique"
description: "Generates a feed for a pdocast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: "The commiter's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ github.actor }}
